---
- name: Ensure chrony is absent
  become: true
  ansible.builtin.package:
    name: chrony
    state: absent

- name: Ensure timesyncd is present
  become: true
  ansible.builtin.package:
    name: systemd-timesyncd
    state: present

- name: Install timesyncd configuration
  become: true
  ansible.builtin.template:
    src: etc_systemd_timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart timesyncd

- name: Enable timesyncd
  become: true
  ansible.builtin.service:
    name: systemd-timesyncd.service
    enabled: true
    state: started
