---
- name: Restart timesyncd
  become: true
  ansible.builtin.service:
    name: systemd-timesyncd.service
    state: restarted

- name: Restart chronyd
  become: true
  ansible.builtin.service:
    name: chronyd.service
    state: restarted
